name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: tools/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/training:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/training:latest
